# Generated by Django 6.0.5 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
