# Generated by Django 6.0.5 on 2026-06-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movie_overview_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.person')),
            ],
            options={
                'ordering': ['department', 'job'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='crewed_in', through='recommender.MovieCrew', to='recommender.person'),
        ),
    ]
