# Generated by Django 6.0.5 on 2026-06-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0004_company_country_movie_companies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='movies', to='recommender.character'),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.character'),
        ),
    ]
