# Generated by Django 6.0.5 on 2026-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_character_movie_characters_alter_moviecast_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
